name: Check Media Usage via GLAM Tools

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual triggering
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  check-usage-glamtools:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install Chrome and ChromeDriver
      run: |
        # Install Chrome
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
        # Chrome version
        google-chrome --version
    
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run GLAM Tools check
      run: |
        python check_media_glamtools.py
    
    - name: Commit and push reports
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add reports/
        TOTAL_CHANGE=$(git diff --cached --name-only --diff-filter=A -z -- 'reports/metadata_*.json' | python - <<'PYCODE'
import json
import sys

paths = sys.stdin.buffer.read().split(b"\0")
total = 0

for raw_path in paths:
    if not raw_path:
        continue
    path = raw_path.decode()
    try:
        with open(path, encoding="utf-8") as fh:
            data = json.load(fh)
    except Exception:
        continue

    value = data.get("diff_label")
    if value is None:
        summary = data.get("summary_differences")
        if isinstance(summary, dict):
            value = summary.get("pages_used")

    if isinstance(value, str):
        value = value.strip()

    try:
        number = int(value)
    except (TypeError, ValueError):
        try:
            number = int(float(value))
        except (TypeError, ValueError):
            continue

    total += abs(number)

print(total)
PYCODE
)
        TOTAL_CHANGE=${TOTAL_CHANGE:-0}
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update media usage report [${TOTAL_CHANGE}] - $(date +'%Y-%m-%d')"
        fi
        git pull --rebase origin main
        git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload reports as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: media-usage-reports-${{ github.run_number }}
        path: reports/
        retention-days: 90
